name: auto sub
permissions:
  contents: write
on:
  schedule:
    - cron: "00 05 * * *"
  # push:
  #   branches: [main]
  workflow_dispatch:

# 设置上海时区
env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 18.11.0
      - name: Install Dependencies
        run: yarn install
      - name: serve
        run: yarn run start
